version: "3.9"

services:
  build-static:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: termizard-build
    volumes:
      - ./dist:/result
    command: ["sh", "-c", "cp -r /out/* /result"]
